import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await page.evaluate(() => sessionStorage.setItem("gfe_loaded", "1"));
await page.reload({ waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: "docs/screenshots/1440-hero-viewport.png" });
await page.click("button[aria-controls='site-menu']");
await page.waitForTimeout(1400);
await page.screenshot({ path: "docs/screenshots/1440-menu.png" });
const m = await browser.newContext({ viewport: { width: 375, height: 812 }, hasTouch: true, isMobile: true });
const mp = await m.newPage();
await mp.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await mp.waitForTimeout(600);
await mp.screenshot({ path: "docs/screenshots/375-preloader.png" });
await mp.waitForTimeout(2500);
await mp.screenshot({ path: "docs/screenshots/375-hero-viewport.png" });
await mp.click("[aria-label='Quick actions'] button >> nth=1");
await mp.waitForTimeout(400);
await mp.screenshot({ path: "docs/screenshots/375-store-picker.png" });
await browser.close();
console.log("viewport shots ok");
