// Vercel Node serverless function — powers the two-step "How much are
// missed calls costing you?" popup (see build/partials.js
// callsPopup/callsPopupScript). Step 1 is a calculator (missed-calls range
// x average job value), step 2 gathers contact info. Sends two emails via
// Resend: one notification to Haider with the estimate and everything
// needed to book a setup call, and an immediate auto-reply to the lead
// recapping their number and pointing them at book-a-call.html.
//
// Requires RESEND_API_KEY as a Vercel env var, and the a2h.info domain
// verified in Resend (Domains → add a2h.info → add the DNS records it
// gives you).
//
// Also writes a row to the `inbound_leads` CRM table via
// lib/inboundLeads.js (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY) so
// api/cron/process-nurture.js can follow up by SMS and api/sms-inbound.js
// can pick up the AI receptionist conversation when the lead texts back.
// Best-effort: a missing/misconfigured Supabase project never blocks the
// response, since the emails above already sent.
//
// Spam defense: honeypot + self-hosted captcha + fill-time check + email
// syntax/disposable-domain/MX validation. See _lib/spam-guard.js for the
// shared helpers and api/captcha-challenge.js for the paired challenge
// issuer.

const {
  honeypotTripped,
  isValidEmailSyntax,
  isDisposableEmail,
  verifyCaptcha,
  domainAcceptsMail,
  looksAutoGenerated,
  MIN_FILL_TIME_MS,
} = require('./_lib/spam-guard');

const {
  normalizePhone,
  computeFitScore,
  insertInboundLead,
} = require('../lib/inboundLeads');

const NOTIFY_TO = 'hhuss786512tx@gmail.com';
const FROM_ADDRESS = 'A2H <hello@a2h.info>';

const escapeHtml = (str) =>
  String(str).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

// Same range keys/midpoints as the client-side calculator in
// build/partials.js callsPopupScript() — recomputed here rather than
// trusting the client-sent estimate, so the numbers in both emails are
// always the source of truth.
const CALLS_LABELS = {
  'under-10': 'Fewer than 10',
  '10-25': '10–25',
  '25-50': '25–50',
  '50-plus': '50 or more',
};
const CALLS_MID = { 'under-10': 7, '10-25': 17, '25-50': 37, '50-plus': 60 };

const VALUE_LABELS = {
  'under-200': 'Under $200',
  '200-500': '$200–$500',
  '500-1500': '$500–$1,500',
  '1500-plus': '$1,500+',
};
const VALUE_MID = { 'under-200': 125, '200-500': 350, '500-1500': 1000, '1500-plus': 2000 };

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method not allowed' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch { body = {}; }
  }
  body = body || {};

  // Honeypot bots fill blindly; pretend success without sending anything
  // so the bot doesn't learn it was caught and start varying its inputs.
  if (honeypotTripped(body)) {
    res.status(200).json({ success: true });
    return;
  }

  const name = String(body.name || '').trim().slice(0, 200);
  const business = String(body.business || '').trim().slice(0, 200);
  const email = String(body.email || '').trim().slice(0, 200);
  const phone = String(body.phone || '').trim().slice(0, 60);
  const landingPage = String(body.landing_page || '').trim().slice(0, 200);

  const callsRaw = String(body.calls_missed || '').trim();
  const valueRaw = String(body.call_value || '').trim();
  const callsKey = CALLS_LABELS[callsRaw] ? callsRaw : '';
  const valueKey = VALUE_LABELS[valueRaw] ? valueRaw : '';
  const monthlyEstimate = callsKey && valueKey ? CALLS_MID[callsKey] * VALUE_MID[valueKey] : null;
  const annualEstimate = monthlyEstimate !== null ? monthlyEstimate * 12 : null;

  // Ad attribution, captured client-side from the landing URL's querystring
  // — absent for organic/direct visitors, that's expected, not an error.
  const gclid = String(body.gclid || '').trim().slice(0, 200);
  const fbclid = String(body.fbclid || '').trim().slice(0, 200);
  const utmSource = String(body.utm_source || '').trim().slice(0, 100);
  const utmCampaign = String(body.utm_campaign || '').trim().slice(0, 100);

  if (!name || !business || !email) {
    res.status(400).json({ error: 'name, business, and email are required' });
    return;
  }

  if (!isValidEmailSyntax(email)) {
    res.status(400).json({ error: 'invalid_email' });
    return;
  }
  if (isDisposableEmail(email)) {
    res.status(400).json({ error: 'disposable_email' });
    return;
  }

  // Only enforced when CAPTCHA_SECRET is actually configured (it is in
  // every environment as of this writing) — a missing secret is an
  // infra issue, not a spam signal, and should never cost a real lead.
  if (process.env.CAPTCHA_SECRET) {
    if (!verifyCaptcha(body.captcha_token, body.captcha_answer)) {
      res.status(400).json({ error: 'captcha_failed' });
      return;
    }
    const elapsed = Number(body.elapsed_ms);
    if (Number.isFinite(elapsed) && elapsed < MIN_FILL_TIME_MS) {
      res.status(400).json({ error: 'too_fast' });
      return;
    }
  }

  // Confirmed-dead email domain (NXDOMAIN with no MX or A fallback) is a
  // hard block; an inconclusive lookup (timeout, resolver hiccup) is not.
  const mailOk = await domainAcceptsMail(String(email).split('@')[1] || '');
  if (mailOk === false) {
    res.status(400).json({ error: 'email_domain_unreachable' });
    return;
  }

  const spamFlagged = looksAutoGenerated(business);

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    res.status(200).json({ success: false, reason: 'not_configured' });
    return;
  }

  const source = utmSource || (gclid ? 'google_ads' : fbclid ? 'meta_ads' : 'organic/direct');
  const sourceLine = `<p><strong>Source:</strong> ${escapeHtml(source)}${utmCampaign ? ` (${escapeHtml(utmCampaign)})` : ''}${landingPage ? ` — popup shown on ${escapeHtml(landingPage)}` : ''}</p>`;

  const callsLine = callsKey ? CALLS_LABELS[callsKey] : 'not specified';
  const valueLine = valueKey ? VALUE_LABELS[valueKey] : 'not specified';
  const estimateLine = monthlyEstimate !== null
    ? `<p><strong>Estimated cost of missed calls:</strong> $${monthlyEstimate.toLocaleString()}/mo (~$${annualEstimate.toLocaleString()}/yr)</p>`
    : '';

  const notifyHtml = `
    <h2>${spamFlagged ? '🚩 Possibly spam — ' : ''}New Missed-Call Cost Report Lead${monthlyEstimate !== null ? ` — ~$${monthlyEstimate.toLocaleString()}/mo` : ''}</h2>
    ${spamFlagged ? '<p style="color:#b91c1c"><strong>Heads up:</strong> the business name looks auto-generated (unusual letter pattern) — worth a second look before treating this as a real lead.</p>' : ''}
    ${sourceLine}
    <p><strong>Name:</strong> ${escapeHtml(name)}</p>
    <p><strong>Business:</strong> ${escapeHtml(business)}</p>
    <p><strong>Email:</strong> ${escapeHtml(email)}</p>
    <p><strong>Phone:</strong> ${escapeHtml(phone) || '—'}</p>
    <p><strong>Calls missed/month:</strong> ${escapeHtml(callsLine)}</p>
    <p><strong>Average job value:</strong> ${escapeHtml(valueLine)}</p>
    ${estimateLine}
    <p>They've already seen their number — get them on the Calendly call to show the AI Receptionist catching those calls live.</p>
  `;

  const leadHtml = `
    <p>Hi ${escapeHtml(name.split(' ')[0] || name)},</p>
    <p>Thanks for running the numbers on ${escapeHtml(business)}!${monthlyEstimate !== null ? ` Based on what you told us, you're potentially losing around <strong>$${monthlyEstimate.toLocaleString()}/month</strong> (about $${annualEstimate.toLocaleString()}/year) to missed calls.` : ''}</p>
    <p>The AI Receptionist answers every call, day or night, books the ones that are ready to book, and logs everything else straight into your CRM — so that number starts closing instead of growing.</p>
    <p>Pick a time and we'll set it up live on a real test call, no obligation: <a href="https://a2h.info/book-a-call.html">a2h.info/book-a-call.html</a>.</p>
    <p>If anything's urgent in the meantime, just reply to this email.</p>
    <p>— Haider, A2H</p>
  `;

  const send = (payload) =>
    fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(payload),
    });

  try {
    const [notifyRes, leadRes] = await Promise.all([
      send({
        from: FROM_ADDRESS,
        to: NOTIFY_TO,
        reply_to: email,
        subject: `${spamFlagged ? '🚩 ' : ''}Missed-Call Cost Report — ${business}${monthlyEstimate !== null ? ` (~$${monthlyEstimate.toLocaleString()}/mo)` : ''}`,
        html: notifyHtml,
      }),
      send({
        from: FROM_ADDRESS,
        to: email,
        reply_to: NOTIFY_TO,
        subject: "Here's your number — and how to fix it",
        html: leadHtml,
      }),
    ]);

    if (!notifyRes.ok) {
      const errText = await notifyRes.text().catch(() => '');
      res.status(200).json({ success: false, reason: 'notify_failed', detail: errText.slice(0, 300) });
      return;
    }

    // Best-effort CRM row — a missing/misconfigured Supabase project must
    // never block the response, the emails above already went out.
    const phoneNormalized = normalizePhone(phone);
    const { fit_score, fit_tier, fit_flags } = computeFitScore({
      business, email, phoneNormalized, url: null, signals: null,
    });
    const notes = `Missed calls: ${callsLine}. Avg job value: ${valueLine}.` +
      (monthlyEstimate !== null ? ` Estimated loss: $${monthlyEstimate.toLocaleString()}/mo (~$${annualEstimate.toLocaleString()}/yr).` : '');
    insertInboundLead({
      name, business, email, phone, phone_normalized: phoneNormalized,
      niche: 'AI Receptionist + CRM (missed-call calculator)', page_count: 'unsure', color_scheme: '',
      reference_sites: '', notes, source,
      fit_score, fit_tier, fit_flags,
      status: 'nurturing', nurture_step: 1, video_sent_at: new Date().toISOString(),
    }).catch((err) => console.error('calls-lead: CRM insert failed', err));

    // The lead auto-reply is best-effort — the notification to Haider
    // (the important part) already went through.
    res.status(200).json({ success: true, leadEmailSent: leadRes.ok });
  } catch (err) {
    res.status(200).json({ success: false, reason: 'exception', detail: String(err).slice(0, 300) });
  }
};
