// Vercel Node serverless function — the detailed "creative brief" a lead
// fills in on mockup.html after opting into the free mockup (see
// api/mockup-request.js for the initial quick-capture popup that sends
// them there). Sends Haider one formatted email with everything needed
// to actually start designing: niche, page count, color direction,
// reference sites, and any must-have features, plus a short confirmation
// back to the lead.
//
// Requires RESEND_API_KEY. Same spam defense as the other two lead
// endpoints — honeypot + self-hosted captcha + fill-time check + email
// validation. See _lib/spam-guard.js and api/captcha-challenge.js.

const {
  honeypotTripped,
  isValidEmailSyntax,
  isDisposableEmail,
  verifyCaptcha,
  domainAcceptsMail,
  looksAutoGenerated,
  MIN_FILL_TIME_MS,
} = require('./_lib/spam-guard');

const NOTIFY_TO = 'hhuss786512tx@gmail.com';
const FROM_ADDRESS = 'A2H <hello@a2h.info>';

const escapeHtml = (str) =>
  String(str).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

const NICHE_LABELS = {
  construction: 'Construction & Contracting',
  medical: 'Medical & Healthcare',
  restaurant: 'Restaurant & Food Service',
  retail: 'Retail & Local Shop',
  professional: 'Professional Services',
  beauty: 'Beauty & Wellness',
  other: 'Other',
};

const PAGE_COUNT_LABELS = {
  '1': 'Just 1 (single-page site)',
  '3-5': '3–5 pages',
  '6-10': '6–10 pages',
  '10+': '10+ pages',
  unsure: 'Not sure yet',
};

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method not allowed' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch { body = {}; }
  }
  body = body || {};

  // Honeypot bots fill blindly; pretend success without sending anything
  // so the bot doesn't learn it was caught and start varying its inputs.
  if (honeypotTripped(body)) {
    res.status(200).json({ success: true });
    return;
  }

  const name = String(body.name || '').trim().slice(0, 200);
  const business = String(body.business || '').trim().slice(0, 200);
  const email = String(body.email || '').trim().slice(0, 200);
  const nicheRaw = String(body.niche || '').trim().toLowerCase();
  const niche = NICHE_LABELS[nicheRaw] ? nicheRaw : '';
  const nicheOther = String(body.niche_other || '').trim().slice(0, 150);
  const pageCountRaw = String(body.page_count || '').trim();
  const pageCount = PAGE_COUNT_LABELS[pageCountRaw] ? pageCountRaw : 'unsure';
  const colorScheme = String(body.color_scheme || '').trim().slice(0, 300);
  const referenceSites = String(body.reference_sites || '').trim().slice(0, 1000);
  const notes = String(body.notes || '').trim().slice(0, 2000);

  if (!name || !business || !email) {
    res.status(400).json({ error: 'name, business, and email are required' });
    return;
  }

  if (!isValidEmailSyntax(email)) {
    res.status(400).json({ error: 'invalid_email' });
    return;
  }
  if (isDisposableEmail(email)) {
    res.status(400).json({ error: 'disposable_email' });
    return;
  }

  // Only enforced when CAPTCHA_SECRET is actually configured (it is in
  // every environment as of this writing) — a missing secret is an
  // infra issue, not a spam signal, and should never cost a real lead.
  if (process.env.CAPTCHA_SECRET) {
    if (!verifyCaptcha(body.captcha_token, body.captcha_answer)) {
      res.status(400).json({ error: 'captcha_failed' });
      return;
    }
    const elapsed = Number(body.elapsed_ms);
    if (Number.isFinite(elapsed) && elapsed < MIN_FILL_TIME_MS) {
      res.status(400).json({ error: 'too_fast' });
      return;
    }
  }

  // Confirmed-dead email domain (NXDOMAIN with no MX or A fallback) is a
  // hard block; an inconclusive lookup (timeout, resolver hiccup) is not.
  const mailOk = await domainAcceptsMail(String(email).split('@')[1] || '');
  if (mailOk === false) {
    res.status(400).json({ error: 'email_domain_unreachable' });
    return;
  }

  const spamFlagged = looksAutoGenerated(business);

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    res.status(200).json({ success: false, reason: 'not_configured' });
    return;
  }

  const nicheLine = niche === 'other' && nicheOther ? nicheOther : (niche ? NICHE_LABELS[niche] : 'not specified');
  const nl2br = (s) => escapeHtml(s).replace(/\n/g, '<br>');

  const notifyHtml = `
    <h2>${spamFlagged ? '🚩 Possibly spam — ' : ''}Mockup Brief — ${escapeHtml(business)}</h2>
    ${spamFlagged ? '<p style="color:#b91c1c"><strong>Heads up:</strong> the business name looks auto-generated (unusual letter pattern) — worth a second look before treating this as a real lead.</p>' : ''}
    <p><strong>Name:</strong> ${escapeHtml(name)}</p>
    <p><strong>Business:</strong> ${escapeHtml(business)}</p>
    <p><strong>Email:</strong> ${escapeHtml(email)}</p>
    <p><strong>Niche/Industry:</strong> ${escapeHtml(nicheLine)}</p>
    <p><strong>Pages wanted:</strong> ${escapeHtml(PAGE_COUNT_LABELS[pageCount])}</p>
    <p><strong>Color scheme:</strong> ${escapeHtml(colorScheme) || '—'}</p>
    <p><strong>Sites they like:</strong><br>${referenceSites ? nl2br(referenceSites) : '—'}</p>
    <p><strong>Anything else:</strong><br>${notes ? nl2br(notes) : '—'}</p>
  `;

  const leadHtml = `
    <p>Hi ${escapeHtml(name.split(' ')[0] || name)},</p>
    <p>Got it — thanks for the details on ${escapeHtml(business)}. We'll use everything you sent when we start building your mockup.</p>
    <p>If you haven't grabbed a time on our calendar yet, you can do that here: <a href="https://a2h.info/mockup.html">a2h.info/mockup.html</a>.</p>
    <p>— Haider, A2H</p>
  `;

  const send = (payload) =>
    fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(payload),
    });

  try {
    const [notifyRes, leadRes] = await Promise.all([
      send({
        from: FROM_ADDRESS,
        to: NOTIFY_TO,
        reply_to: email,
        subject: `${spamFlagged ? '🚩 ' : ''}Mockup Brief — ${business}`,
        html: notifyHtml,
      }),
      send({
        from: FROM_ADDRESS,
        to: email,
        reply_to: NOTIFY_TO,
        subject: 'Got your details — A2H',
        html: leadHtml,
      }),
    ]);

    if (!notifyRes.ok) {
      const errText = await notifyRes.text().catch(() => '');
      res.status(200).json({ success: false, reason: 'notify_failed', detail: errText.slice(0, 300) });
      return;
    }

    // The lead confirmation is best-effort, same caveat as the other two
    // endpoints — the notification to Haider already went through.
    res.status(200).json({ success: true, leadEmailSent: leadRes.ok });
  } catch (err) {
    res.status(200).json({ success: false, reason: 'exception', detail: String(err).slice(0, 300) });
  }
};
