// Vercel Node serverless function — powers the two-step "What kind of
// website do you want?" / "How do we reach you?" mockup popup (see
// build/partials.js leadPopup/leadPopupScript). A single submit carries
// both the creative brief (niche, page count, color scheme, reference
// sites, notes) and the contact info gathered across the two steps.
// Sends two emails via Resend: one notification to Haider with
// everything needed to actually start building, and an immediate
// auto-reply to the lead confirming next steps and pointing them at
// mockup.html to book a time.
//
// Requires RESEND_API_KEY as a Vercel env var, and the a2h.info domain
// verified in Resend (Domains → add a2h.info → add the DNS records it
// gives you).
//
// Also writes a row to the `inbound_leads` CRM table via
// lib/inboundLeads.js (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY) so
// api/cron/process-nurture.js can follow up and api/booking-confirmed.js
// can mark it booked. Best-effort: a missing/misconfigured Supabase
// project never blocks the response, since the emails above already sent.
//
// Spam defense: honeypot + self-hosted captcha + fill-time check + email
// syntax/disposable-domain/MX validation. See _lib/spam-guard.js for the
// shared helpers and api/captcha-challenge.js for the paired challenge
// issuer.

const {
  honeypotTripped,
  isValidEmailSyntax,
  isDisposableEmail,
  verifyCaptcha,
  domainAcceptsMail,
  looksAutoGenerated,
  MIN_FILL_TIME_MS,
} = require('./_lib/spam-guard');

const {
  normalizePhone,
  computeFitScore,
  insertInboundLead,
  PRECALL_VIDEO_URL,
} = require('../lib/inboundLeads');

const NOTIFY_TO = 'hhuss786512tx@gmail.com';
const FROM_ADDRESS = 'A2H <hello@a2h.info>';

const escapeHtml = (str) =>
  String(str).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

const NICHE_LABELS = {
  construction: 'Construction & Contracting',
  medical: 'Medical & Healthcare',
  restaurant: 'Restaurant & Food Service',
  retail: 'Retail & Local Shop',
  professional: 'Professional Services',
  beauty: 'Beauty & Wellness',
  other: 'Other',
};

const PAGE_COUNT_LABELS = {
  '1': 'Just 1 (single-page site)',
  '3-5': '3–5 pages',
  '6-10': '6–10 pages',
  '10+': '10+ pages',
  unsure: 'Not sure yet',
};

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method not allowed' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch { body = {}; }
  }
  body = body || {};

  // Honeypot bots fill blindly; pretend success without sending anything
  // so the bot doesn't learn it was caught and start varying its inputs.
  if (honeypotTripped(body)) {
    res.status(200).json({ success: true });
    return;
  }

  const name = String(body.name || '').trim().slice(0, 200);
  const business = String(body.business || '').trim().slice(0, 200);
  const email = String(body.email || '').trim().slice(0, 200);
  const phone = String(body.phone || '').trim().slice(0, 60);
  const landingPage = String(body.landing_page || '').trim().slice(0, 200);

  // The "what kind of website" brief, gathered in step 1 of the popup.
  const nicheRaw = String(body.niche || '').trim().toLowerCase();
  const niche = NICHE_LABELS[nicheRaw] ? nicheRaw : '';
  const nicheOther = String(body.niche_other || '').trim().slice(0, 150);
  const pageCountRaw = String(body.page_count || '').trim();
  const pageCount = PAGE_COUNT_LABELS[pageCountRaw] ? pageCountRaw : 'unsure';
  const colorScheme = String(body.color_scheme || '').trim().slice(0, 300);
  const referenceSites = String(body.reference_sites || '').trim().slice(0, 1000);
  const notes = String(body.notes || '').trim().slice(0, 2000);

  // Ad attribution, captured client-side from the landing URL's querystring
  // — absent for organic/direct visitors, that's expected, not an error.
  const gclid = String(body.gclid || '').trim().slice(0, 200);
  const fbclid = String(body.fbclid || '').trim().slice(0, 200);
  const utmSource = String(body.utm_source || '').trim().slice(0, 100);
  const utmCampaign = String(body.utm_campaign || '').trim().slice(0, 100);

  if (!name || !business || !email) {
    res.status(400).json({ error: 'name, business, and email are required' });
    return;
  }

  if (!isValidEmailSyntax(email)) {
    res.status(400).json({ error: 'invalid_email' });
    return;
  }
  if (isDisposableEmail(email)) {
    res.status(400).json({ error: 'disposable_email' });
    return;
  }

  // Only enforced when CAPTCHA_SECRET is actually configured (it is in
  // every environment as of this writing) — a missing secret is an
  // infra issue, not a spam signal, and should never cost a real lead.
  if (process.env.CAPTCHA_SECRET) {
    if (!verifyCaptcha(body.captcha_token, body.captcha_answer)) {
      res.status(400).json({ error: 'captcha_failed' });
      return;
    }
    const elapsed = Number(body.elapsed_ms);
    if (Number.isFinite(elapsed) && elapsed < MIN_FILL_TIME_MS) {
      res.status(400).json({ error: 'too_fast' });
      return;
    }
  }

  // Confirmed-dead email domain (NXDOMAIN with no MX or A fallback) is a
  // hard block; an inconclusive lookup (timeout, resolver hiccup) is not.
  const mailOk = await domainAcceptsMail(String(email).split('@')[1] || '');
  if (mailOk === false) {
    res.status(400).json({ error: 'email_domain_unreachable' });
    return;
  }

  const spamFlagged = looksAutoGenerated(business);

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    res.status(200).json({ success: false, reason: 'not_configured' });
    return;
  }

  const source = utmSource || (gclid ? 'google_ads' : fbclid ? 'meta_ads' : 'organic/direct');
  const sourceLine = `<p><strong>Source:</strong> ${escapeHtml(source)}${utmCampaign ? ` (${escapeHtml(utmCampaign)})` : ''}${landingPage ? ` — popup shown on ${escapeHtml(landingPage)}` : ''}</p>`;

  const nicheLine = niche === 'other' && nicheOther ? nicheOther : (niche ? NICHE_LABELS[niche] : 'not specified');
  const nl2br = (s) => escapeHtml(s).replace(/\n/g, '<br>');

  const notifyHtml = `
    <h2>${spamFlagged ? '🚩 Possibly spam — ' : ''}New Free Mockup Request</h2>
    ${spamFlagged ? '<p style="color:#b91c1c"><strong>Heads up:</strong> the business name looks auto-generated (unusual letter pattern) — worth a second look before treating this as a real lead.</p>' : ''}
    ${sourceLine}
    <p><strong>Name:</strong> ${escapeHtml(name)}</p>
    <p><strong>Business:</strong> ${escapeHtml(business)}</p>
    <p><strong>Email:</strong> ${escapeHtml(email)}</p>
    <p><strong>Phone:</strong> ${escapeHtml(phone) || '—'}</p>
    <p><strong>Niche/Industry:</strong> ${escapeHtml(nicheLine)}</p>
    <p><strong>Pages wanted:</strong> ${escapeHtml(PAGE_COUNT_LABELS[pageCount])}</p>
    <p><strong>Color scheme:</strong> ${escapeHtml(colorScheme) || '—'}</p>
    <p><strong>Sites they like:</strong><br>${referenceSites ? nl2br(referenceSites) : '—'}</p>
    <p><strong>Anything else:</strong><br>${notes ? nl2br(notes) : '—'}</p>
    <p>Build them a homepage mockup within 2–3 days, then get them on the Calendly call they were routed to on mockup.html.</p>
  `;

  const leadHtml = `
    <p>Hi ${escapeHtml(name.split(' ')[0] || name)},</p>
    <p>Thanks for telling us about ${escapeHtml(business)}! We're getting started on a free homepage mockup made specifically for your business — no charge, no obligation.</p>
    <p>It'll be ready in 2–3 days. In the meantime, here's a quick video on what to expect: <a href="${escapeHtml(PRECALL_VIDEO_URL)}">${escapeHtml(PRECALL_VIDEO_URL)}</a></p>
    <p>If you haven't already, pick a time on our calendar and we'll walk you through it live: <a href="https://a2h.info/mockup.html">a2h.info/mockup.html</a>.</p>
    <p>If anything's urgent in the meantime, just reply to this email.</p>
    <p>— Haider, A2H</p>
  `;

  const send = (payload) =>
    fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(payload),
    });

  try {
    const [notifyRes, leadRes] = await Promise.all([
      send({
        from: FROM_ADDRESS,
        to: NOTIFY_TO,
        reply_to: email,
        subject: `${spamFlagged ? '🚩 ' : ''}Free Mockup Request — ${business}`,
        html: notifyHtml,
      }),
      send({
        from: FROM_ADDRESS,
        to: email,
        reply_to: NOTIFY_TO,
        subject: "You're in — your free A2H mockup is underway",
        html: leadHtml,
      }),
    ]);

    if (!notifyRes.ok) {
      const errText = await notifyRes.text().catch(() => '');
      res.status(200).json({ success: false, reason: 'notify_failed', detail: errText.slice(0, 300) });
      return;
    }

    // Best-effort CRM row — a missing/misconfigured Supabase project must
    // never block the response, the emails above already went out.
    const phoneNormalized = normalizePhone(phone);
    const { fit_score, fit_tier, fit_flags } = computeFitScore({
      business, email, phoneNormalized, url: null, signals: null,
    });
    insertInboundLead({
      name, business, email, phone, phone_normalized: phoneNormalized,
      niche: nicheLine, page_count: pageCount, color_scheme: colorScheme,
      reference_sites: referenceSites, notes, source,
      fit_score, fit_tier, fit_flags,
      status: 'nurturing', nurture_step: 1, video_sent_at: new Date().toISOString(),
    }).catch((err) => console.error('mockup-request: CRM insert failed', err));

    // The lead auto-reply is best-effort — the notification to Haider
    // (the important part) already went through.
    res.status(200).json({ success: true, leadEmailSent: leadRes.ok });
  } catch (err) {
    res.status(200).json({ success: false, reason: 'exception', detail: String(err).slice(0, 300) });
  }
};
